### ISSUE TITLE
The issue regarding the number of permutations of point sets

### ISSUE THREAD

**Issue by sxs505** [woodfrog/maptracker#6]
In the code, when observing the ground truth part, if there are 20 points in a line element of a vectors, why are there 38 relations corresponding to it, given that according to maptr's viewpoint, the permutation of point sets should result in 2N?

**Comment by woodfrog** [comment]
This part is from StreamMapNet. If I remember correctly:  because the first and last points of a polygon are the same (duplicated), there are only 19 different coordinates, so we have 38=19*2 permutations. For polylines, there will be only 2 permutations. All things are equivalent to MapTR's viewpoint.
